version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  cache:
    paths:
      - 'node_modules/**/*' # Cache node_modules for faster npm installs
      - '.next/cache/**/*'   # Cache Next.js .next/cache directory
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - 'node_modules/**/*'
      - '.next/cache/**/*'
  appRoot: ./  # Adjust this path to your project's root directory
